import { registry } from "@/config/logic";
const { visuals, tokens: designTokens } = registry;
const text = designTokens.primitive.typography.text;
const borderToken = designTokens.semantic.border.default;

// Static styling authority only.
// No functions, no params, no branching.
// If styling depends on runtime state, move that logic out and expose only static variants here.
// Surface dimension only: container shape, background, elevation, blur.
// Static strings only. No runtime composition helpers.

const transition = designTokens.primitive.motion;

const primitiveTokens = {
    radius: {
        panel: "rounded-panel",
        modal: "rounded-modal",
        raised: "rounded-2xl",
        full: "rounded-full",
        pill: "rounded-pill",
        tight: "rounded-tight",
        medium: "rounded-md",
    },
    blur: {
        panel: "blur-glass",
        soft: "backdrop-blur-sm",
        floating: "backdrop-blur-xl",
    },
    elevation: {
        panel: "shadow-small",
        overlay: "shadow-medium",
        floating: "shadow-visual-large",
        menu: "shadow-menu-large",
    },
    opacity: {
        canvas: "bg-transparent",
        subtle: "bg-content1/10",
        raised: "bg-content1/55",
        modal: "bg-content1/80",
        overlay: "bg-background/90",
        codeInline: "bg-content1/20",
    },
    border: {
        subtle: "border border-default/10",
        default: "border border-default/20",
        strong: "border border-default/50",
    },
    motion: designTokens.primitive.motion,
    typography: designTokens.primitive.typography,
} as const;

const semanticTokens = {
    text: {
        heading: text.heading,
        headingSection: text.headingSection,
        bodyStrong: text.bodyStrong,
        body: text.body,
        label: text.label,
        muted: text.bodyMuted,
        caption: text.caption,
        code: text.code,
    },
    state: {
        disabled: visuals.state.disabled,
        muted: visuals.state.muted,
        ghost: visuals.state.ghost,
    },
    border: {
        subtle: primitiveTokens.border.subtle,
        default: primitiveTokens.border.default,
        strong: primitiveTokens.border.strong,
    },
    chrome: {
        edgeTop: "border-t border-default/50",
        edgeBottom: "border-b border-default/50",
        divider: "border-default/20",
        sticky: `sticky top-0 z-sticky bg-background/80 ${primitiveTokens.blur.soft}`,
    },
    surface: {
        canvas: primitiveTokens.opacity.canvas,
        subtle: primitiveTokens.opacity.subtle,
        raised: primitiveTokens.opacity.raised,
        modal: primitiveTokens.opacity.modal,
        overlay: primitiveTokens.opacity.overlay,
    },
} as const;

export const tokens = {
    primitive: primitiveTokens,
    semantic: semanticTokens,
} as const;

const menuSurfaceList = "overflow-hidden outline-none ring-0";
const menuItemSurface =
    "rounded-panel px-panel py-tight text-scaled font-medium cursor-pointer " +
    "outline-none focus:outline-none focus-visible:outline-none " +
    "ring-0 focus:ring-0 focus-visible:ring-0 " +
    "transition-all duration-150 ease-out " +
    "hover:bg-content2 hover:text-foreground hover:translate-y-[-1px] " +
    "focus-visible:bg-content2 focus-visible:text-foreground " +
    "active:bg-content3 active:translate-y-0";
const menuListClassNames = {
    base: "outline-none ring-0",
    list: menuSurfaceList,
} as const;
const menuItemClassNames = { base: menuItemSurface } as const;
const menuSectionHeading = semanticTokens.text.label;
const menuPanelHeader = `px-panel py-tight border-b border-content1/10 mb-tight flex items-center gap-tools`;
const menuPanelHeaderIcon = "text-foreground/30";
const menuPanelHeaderText = `${text.label} text-foreground/40 truncate`;
const menuActionButtonBase = `w-full flex items-center gap-tools px-panel py-tight rounded-xl ${text.buttonText}`;
const menuActionButton = `${menuActionButtonBase} ${visuals.interactive.menuItem}`;
const menuActionButtonDanger = `${menuActionButtonBase} text-danger ${visuals.interactive.menuItemDanger} border-t border-content1/10 mt-tight`;
const statusChipPattern = {
    base: "h-status-chip px-tight inline-flex items-center justify-center gap-tools whitespace-nowrap",
    content: "font-bold text-scaled tracking-wider whitespace-nowrap text-foreground",
    container: "min-w-0 w-full flex items-center justify-center h-full",
    contentWrap: "flex items-center justify-center gap-tools",
    warningIcon: "toolbar-icon-size-md text-warning",
    currentIcon: "text-current",
    label: "truncate max-w-full",
} as const;
const tableHeaderPattern = {
    compactCell: "px-panel py-tight",
    sectionDividerCell: "border-b border-default/10 px-tight py-panel",
    iconCell: "border-b border-default/10 py-panel pl-panel pr-tight",
    statusCell: "border-b border-default/10 py-panel pl-tight pr-panel text-right",
} as const;
const workbenchShell = `acrylic shadow-inner ${primitiveTokens.elevation.panel}`;
const panelInset = `${primitiveTokens.radius.panel} ${primitiveTokens.border.subtle} overflow-hidden ${semanticTokens.surface.subtle}`;
const panelRaised = `${primitiveTokens.radius.raised} border ${borderToken} ${semanticTokens.surface.subtle}`;
const panelInfo = `${primitiveTokens.radius.raised} border ${borderToken} ${semanticTokens.surface.canvas}`;
const panelWorkflow = `${primitiveTokens.radius.raised} border ${borderToken} ${semanticTokens.surface.raised}`;
const panelSidebar = `flex flex-col border-r ${borderToken} ${semanticTokens.surface.raised} ${primitiveTokens.blur.panel}`;
const statusModulePanel = `${primitiveTokens.radius.modal} border ${borderToken} ${semanticTokens.surface.subtle} ${primitiveTokens.blur.soft}`;
const modalBaseClassNames = {
    base: `glass-panel surface-layer-2 text-foreground ${primitiveTokens.elevation.floating} ${primitiveTokens.radius.modal} flex flex-col overflow-hidden ${primitiveTokens.border.default}`,
} as const;
const modalCompactClassNames = {
    base: `${modalBaseClassNames.base} w-full max-w-modal-compact`,
} as const;
const modalBaseWrapperHiddenClassNames = {
    base: modalBaseClassNames.base,
    wrapper: "overflow-hidden",
} as const;
const modalChromeClassNames = {
    body: "p-tight",
    header: `p-none select-none ${primitiveTokens.blur.panel}`,
    footer: "p-none select-none",
} as const;
const tooltipControl = {
    content: `${semanticTokens.surface.modal} border ${borderToken} ${primitiveTokens.blur.floating} ${primitiveTokens.elevation.floating} ${primitiveTokens.radius.raised} px-panel py-tight text-scaled leading-tight text-foreground/90`,
    arrow: semanticTokens.surface.modal,
} as const;
const mapOverlaySurface = `${primitiveTokens.border.default} ${semanticTokens.surface.raised} ${primitiveTokens.blur.floating} ${primitiveTokens.elevation.overlay}`;
const mapOverlayRadius = primitiveTokens.radius.raised;
const mapOverlayCard = `${mapOverlaySurface} ${mapOverlayRadius} px-panel py-tight`;
const controlChrome = {
    dialogHeader: `${semanticTokens.chrome.edgeBottom} flex flex-nowrap items-center justify-between gap-tools px-panel py-tight`,
    dialogFooter: `${semanticTokens.chrome.edgeTop} flex items-center justify-between gap-tools px-panel py-tight`,
    workflowFooter: `${semanticTokens.chrome.edgeTop} flex flex-col gap-panel px-panel py-tight sm:flex-row sm:items-center sm:justify-between`,
    headerPassive: `${semanticTokens.chrome.edgeBottom} select-none`,
    footerEnd: `${semanticTokens.chrome.edgeTop} flex justify-end gap-tools`,
    footerActionsPadded: `${semanticTokens.chrome.edgeTop} px-stage py-panel flex items-center justify-end gap-tools`,
} as const;
const modalLayoutControl = {
    contentWrapper: "h-full flex flex-col",
    row: "flex flex-row flex-1 min-h-0 overflow-hidden relative",
    headerLead: "flex min-w-0 flex-1 items-center gap-panel",
    titleWrap: "flex min-w-0 flex-col overflow-hidden",
    body: "flex flex-col gap-stage p-panel",
    bodyFlush: "flex min-h-0 flex-1 flex-col p-none overflow-hidden",
    sectionStack: "flex flex-col gap-tight",
    insetStack: "flex flex-col gap-tight",
    insetItem: `${primitiveTokens.radius.panel} ${primitiveTokens.border.default} p-tight`,
    locationRow: `flex items-center gap-tools surface-layer-1 ${primitiveTokens.radius.panel} p-tight`,
    footerButtonRow: "flex gap-tools ml-auto",
    footerGroup: "flex shrink-0 items-center gap-tools",
    contentStack: "flex flex-col space-y-stage sm:space-y-stage pb-stage",
    scrollContent: "flex-1 min-h-0 overflow-y-auto scrollbar-hide",
} as const;
const panelControl = {
    canvas: "glass-panel surface-layer-0 text-foreground",
    workbench: `glass-panel surface-layer-1 text-foreground ${semanticTokens.surface.canvas}`,
    base: `${primitiveTokens.radius.panel} ${primitiveTokens.border.subtle} overflow-hidden ${semanticTokens.surface.subtle}`,
    pane: `flex flex-col min-h-0 overflow-hidden ${primitiveTokens.radius.panel} ${primitiveTokens.border.default} ${primitiveTokens.elevation.panel} ${semanticTokens.surface.raised}`,
    inset: `surface-layer-1 ${primitiveTokens.radius.panel} p-tight`,
    insetFull: `surface-layer-1 ${primitiveTokens.radius.full} p-tight`,
    insetBordered: `${primitiveTokens.radius.panel} ${primitiveTokens.border.default} p-tight`,
    raised: panelRaised,
    info: panelInfo,
    workflow: panelWorkflow,
    sidebar: panelSidebar,
    statusModule: statusModulePanel,
    overlay: `${primitiveTokens.border.default} ${semanticTokens.surface.overlay} ${primitiveTokens.blur.floating} ${primitiveTokens.elevation.overlay}`,
    glass: "glass-panel surface-layer-1 text-foreground",
    floating: "glass-panel surface-layer-2 text-foreground",
} as const;
const modalControl = {
    surface: {
        baseClassNames: modalBaseClassNames,
        compactClassNames: modalCompactClassNames,
        baseWrapperHiddenClassNames: modalBaseWrapperHiddenClassNames,
        chromeClassNames: modalChromeClassNames,
        baseClass: modalBaseClassNames.base,
    },
    chrome: {
        default: modalChromeClassNames,
        dialog: controlChrome,
    },
} as const;
const menuControl = {
    surface: `glass-panel surface-layer-2 text-foreground outline-none ring-0 overflow-hidden ${primitiveTokens.elevation.menu} ${primitiveTokens.radius.modal} ${primitiveTokens.border.default} p-tight`,
    dirPickerSurface: `min-w-dir-picker glass-panel surface-layer-2 text-foreground outline-none ring-0 overflow-hidden ${primitiveTokens.elevation.menu} ${primitiveTokens.radius.modal} ${primitiveTokens.border.default} p-tight`,
    minWidthSurface: "min-w-(--tt-menu-min-width)",
    list: {
        classNames: menuListClassNames,
    },
    item: {
        base: menuItemSurface,
        split: {
            base: `${menuItemSurface} flex items-center justify-between`,
        } as const,
        strong: "font-semibold",
        nested: "pl-stage",
        pinned: "font-semibold text-foreground",
        selectedPrimary: "bg-primary/15 text-primary",
        flagInlineWrap: "text-lg leading-none",
        checkIconPrimary: "text-primary",
    },
    chrome: {
        sectionHeading: menuSectionHeading,
        header: menuPanelHeader,
        headerIcon: menuPanelHeaderIcon,
        headerText: menuPanelHeaderText,
    },
    action: {
        iconButton: `p-tight inline-flex items-center justify-center ${transition.fast} toolbar-icon-hit`,
        windowButtonBase: "flex h-full items-center justify-center rounded-none border-0 px-0 transition-none window-control-button-width",
        windowButtonNeutral: "text-foreground/60 hover:text-foreground hover:bg-primary/10",
        windowButtonDanger: "text-foreground/60 hover:text-danger hover:bg-danger/20",
        base: menuActionButton,
        danger: menuActionButtonDanger,
    },
} as const;
const tableControl = {
    header: tableHeaderPattern,
    contextStatusBadge:
        "inline-flex max-w-full items-center rounded-panel border border-default/10 bg-content1/35 px-tight py-tight",
    progress: {
        track: "bg-content2/50 h-full",
        paused: "bg-gradient-to-r from-warning/50 to-warning",
        seeding: "bg-gradient-to-r from-primary/50 to-primary",
        active: "bg-gradient-to-r from-success/50 to-success",
    },
    shadowOverlay: primitiveTokens.elevation.overlay,
} as const;
const statusChipControl = statusChipPattern;
export const surface = {
    // Temporary non-authoritative shell for current imports. Source of truth is `tokens` + `control`.
    dial: tokens.primitive,
    role: {
        workbench: panelControl.workbench,
        panel: panelControl.base,
        pane: panelControl.pane,
        modal: modalControl.surface.baseClass,
        inset: panelControl.inset,
        menu: menuControl.surface,
        overlay: panelControl.overlay,
    },
    surface: {
        workbenchShell: workbenchShell,
        panelInset: panelControl.base,
        tooltip: tooltipControl.content,
        statusModule: panelControl.statusModule,
        panelRaised: panelControl.raised,
        panelMuted: panelControl.raised,
        panelInfo: panelControl.info,
        panelWorkflow: panelControl.workflow,
        sidebarPanel: panelControl.sidebar,
    },
    state: tokens.semantic.state,
    text: tokens.semantic.text,
    tooltip: tooltipControl,
    chrome: tokens.semantic.chrome,
    chromeEx: modalControl.chrome.dialog,
    modal: modalControl.surface,
    menu: {
        surface: menuControl.surface,
        dirPickerSurface: menuControl.dirPickerSurface,
        minWidthSurface: menuControl.minWidthSurface,
        listClassNames: menuControl.list.classNames,
        itemClassNames: { base: menuControl.item.base } as const,
        itemSplitClassNames: menuControl.item.split,
        itemStrong: menuControl.item.strong,
        itemNested: menuControl.item.nested,
        itemPinned: menuControl.item.pinned,
        itemSelectedPrimary: menuControl.item.selectedPrimary,
        flagInlineWrap: menuControl.item.flagInlineWrap,
        checkIconPrimary: menuControl.item.checkIconPrimary,
        sectionHeading: menuControl.chrome.sectionHeading,
        panelHeader: menuControl.chrome.header,
        panelHeaderIcon: menuControl.chrome.headerIcon,
        panelHeaderText: menuControl.chrome.headerText,
        actionButton: menuControl.action.base,
        dangerActionButton: menuControl.action.danger,
    },
    atom: {
        textCurrent: "text-current",
        objectContain: "object-contain",
        codeInline: `${primitiveTokens.opacity.codeInline} px-tight py-tight rounded`,
        insetRounded: panelControl.inset,
        insetRoundedFull: panelControl.insetFull,
        insetBorderedItem: panelControl.insetBordered,
        glassPanel: panelControl.glass,
        shadowPanel: tableControl.shadowOverlay,
        progressTrack: tableControl.progress.track,
        progressIndicatorPaused: tableControl.progress.paused,
        progressIndicatorSeeding: tableControl.progress.seeding,
        progressIndicatorActive: tableControl.progress.active,
    },
} as const;

const bgTransparent = "bg-transparent";
const bgBackground40 = "bg-background/40";
const bgBackground90 = "bg-background/90";
const bgContent110 = "bg-content1/10";
const bgContent120 = "bg-content1/20";
const bgPrimary10 = "bg-primary/10";
const roundedPanel = primitiveTokens.radius.panel;
const roundedRaised = primitiveTokens.radius.raised;
const roundedFull = primitiveTokens.radius.full;
const roundedPill = primitiveTokens.radius.pill;
const roundedTight = primitiveTokens.radius.tight;
const roundedMedium = primitiveTokens.radius.medium;
const workbenchMainShell = `${workbenchShell} surface-layer-2 `;
const workbenchIslandShell = `glass-panel text-foreground ${workbenchShell} border border-default/45`;

export const modal = {
    baseClassNames: surface.modal.baseClassNames,
    compactClassNames: surface.modal.compactClassNames,
    settingsModalBaseFull: `${surface.modal.baseClass} flex flex-row max-h-full max-w-full`,
    settingsModalBaseRpc: `${surface.modal.baseClass} flex flex-row h-settings max-h-settings min-h-settings`,
    settingsModalWrapper: "overflow-hidden",
    settingsModalClassNamesFull: {
        base: `${surface.modal.baseClass} flex flex-row max-h-full max-w-full`,
        wrapper: "overflow-hidden",
    } as const,
    settingsModalClassNamesRpc: {
        base: `${surface.modal.baseClass} flex flex-row h-settings max-h-settings min-h-settings`,
        wrapper: "overflow-hidden",
    } as const,
    addTorrentModalBase: `${surface.modal.baseClass} w-full`,
    addTorrentModalHeightFull: "h-full",
    addTorrentModalHeightDefault: "max-h-modal-body",
    addTorrentModalChromeClassNames: surface.modal.chromeClassNames,
    addTorrentBodyPanelsBase: "flex flex-col flex-1 min-h-settings",
    addTorrentBodyPanelsFullscreen: "h-full min-h-0",
    sidebar: `${surface.surface.sidebarPanel} ${transition.slow} absolute inset-y-0 left-0 z-sticky settings-sidebar-shell sm:relative sm:translate-x-0`,
    sidebarHidden: "-translate-x-full",
    sidebarVisible: "translate-x-0",
    sidebarHeader: "p-stage border-b border-content1/10 flex justify-between items-center h-modal-header shrink-0",
    headingFont: "tt-navbar-tab-font",
    iconMd: "toolbar-icon-size-md",
    iconSm: "toolbar-icon-size-sm shrink-0",
    iconLg: "toolbar-icon-size-lg",
    footerEnd: surface.chromeEx.footerEnd,
    sidebarCloseButton: "sm:hidden text-foreground/50",
    sidebarBody: "flex-1 px-panel py-panel space-y-tight overflow-y-auto scrollbar-hide",
    tabButtonBase: `w-full flex items-center gap-panel px-panel py-panel ${roundedPanel} ${transition.medium} group relative`,
    tabButtonActive: `${bgPrimary10} text-primary font-semibold`,
    tabButtonInactive: `text-foreground/60 font-medium ${visuals.interactive.navItem}`,
    tabIcon: "shrink-0 toolbar-icon-size-md",
    tabIconActive: "text-primary",
    tabIconInactive: "text-foreground/50",
    tabIndicator: "absolute settings-tab-indicator bg-primary rounded-r-pill",
    versionWrapper: "p-panel border-t border-content1/10 shrink-0",
    versionText: `${text.codeCaption} text-foreground/30`,
    header: `${surface.chrome.edgeBottom} ${surface.chrome.sticky} shrink-0 h-modal-header flex items-center justify-between px-stage`,
    headerLead: "flex items-center gap-tools",
    headerLeadPrimaryIcon: "text-primary",
    hintText: `${text.bodyMuted} leading-relaxed`,
    headerTitleWrap: "flex min-w-0 flex-col overflow-hidden",
    headerMobileBack: "sm:hidden -ml-tight text-foreground/50",
    desktopClose: `text-foreground/40 hidden sm:flex ${visuals.interactive.dismiss}`,
    contentStack: "flex flex-col space-y-stage sm:space-y-stage pb-stage",
    scrollContent: "flex-1 min-h-0 overflow-y-auto scrollbar-hide",
    alert: "mb-panel px-panel py-tight",
    inlineAlert: "px-panel py-tight",
    footerButtonRow: "flex gap-tools ml-auto",
    dialogHeader: surface.chromeEx.dialogHeader,
    dialogHeaderLead: "flex min-w-0 flex-1 items-center gap-panel",
    dialogHeaderIconWrap: surface.atom.insetRoundedFull,
    dialogHeaderWarningIcon: "toolbar-icon-size-md text-warning",
    dialogBody: "flex flex-col gap-stage p-panel",
    dialogBodyFlush: "flex min-h-0 flex-1 flex-col p-none overflow-hidden",
    dialogSectionStack: "flex flex-col gap-tight",
    dialogInsetStack: "flex flex-col gap-tight",
    dialogInsetItem: surface.atom.insetBorderedItem,
    dialogLocationRow: `flex items-center gap-tools ${surface.atom.insetRounded}`,
    dialogLocationIcon: "toolbar-icon-size-md text-foreground",
    dialogLocationLabel: `${text.code} truncate`,
    dialogInsetTitle: `${text.bodySmall} font-semibold text-foreground`,
    dialogInsetLabel: `${text.bodySmall} font-medium text-foreground truncate`,
    dialogInsetDescription: `${text.bodySmall} truncate`,
    dialogOutcomePanel: `${surface.atom.insetRounded} ${text.bodySmall}`,
    dialogFooter: surface.chromeEx.dialogFooter,
    dialogFooterGroup: "flex shrink-0 items-center gap-tools",
    dialogSecondaryAction: "font-medium text-foreground",
    dialogPrimaryAction: "font-bold",
    contentWrapper: "h-full flex flex-col",
    layout: "flex flex-row flex-1 min-h-0 overflow-hidden relative",
    mainPane: `flex-1 min-h-0 flex flex-col ${bgContent110} blur-glass relative w-full`,
    workflow: {
        gateRoot: "flex flex-col h-full",
        header: surface.chromeEx.dialogHeader,
        titleStack: "flex flex-col overflow-hidden gap-tight",
        sourceLabelCaption: `${text.caption} truncate font-mono leading-tight`,
        sourceMutedLabel: `${text.codeMuted} text-foreground/50 truncate leading-tight`,
        iconMd: "toolbar-icon-size-md",
        iconMdPrimary: "toolbar-icon-size-md text-primary",
        iconLgPrimary: "toolbar-icon-size-lg text-primary",
        iconMdSuccess: "toolbar-icon-size-md text-success",
        iconMdWarning: "toolbar-icon-size-md text-warning",
        iconAlert: "toolbar-icon-size-md shrink-0",
        iconAlertMuted: "toolbar-icon-size-md shrink-0 text-foreground/50",
        warningTone: "text-warning",
        footerAlertText: `${text.bodyStrong} truncate`,
        headerIconButton: `text-foreground/60 ${visuals.interactive.textReveal}`,
        gateBody: "flex-1 min-h-0 flex items-center justify-center",
        gateContent: "w-full max-w-modal",
        formRoot: "flex flex-col min-h-0 flex-1 relative",
        submitOverlay: `absolute inset-0 flex flex-col items-center justify-center text-foreground/50 gap-tools z-modal-internal ${bgBackground40} blur-glass`,
        submitHintMuted: `${text.codeMuted} text-foreground/40 text-center max-w-modal`,
        submitWarningTitleCaption: `${text.codeCaption} text-foreground/70`,
        submitActions: "flex gap-tools",
        headerActions: "flex items-center gap-tools",
        headerDivider: `h-status-chip w-px ${bgContent110} mx-tight`,
        body: "flex-1 min-h-0 relative p-none",
        dropOverlay:
            "absolute inset-0 z-drop-overlay bg-primary/20 blur-glass border-divider border-primary border-dashed m-panel rounded-panel flex items-center justify-center pointer-events-none",
        dropOverlayChip:
            "bg-background px-stage py-tight rounded-pill shadow-small flex items-center gap-tools animate-pulse",
        panelGroup: "flex-1 min-h-0",
        paneHandle: `w-add-modal-pane-gap flex items-stretch justify-center z-panel ${transition.fast} group focus:outline-none relative border-x border-default/20 hover:border-primary/45`,
        paneHandleEnabled: "cursor-col-resize",
        settingsPanelCollapsed: "min-w-0 w-0",
        resizeHandleBarBase: `h-full w-divider ${transition.fast}`,
        resizeHandleBarActive: "bg-primary",
        resizeHandleBarIdle: "bg-primary/70 group-hover:bg-primary/85",
        resizeHandleBarWrap: "absolute inset-x-0 py-panel flex justify-center pointer-events-none",
        settingsPanel: `${surface.atom.glassPanel} border-none shadow-none flex flex-col min-h-0 overflow-hidden`,
        filePanel:
            "glass-panel surface-layer-2 text-foreground border-none shadow-none flex flex-col min-h-0 overflow-hidden",
        filePanelContent: "flex flex-col flex-1 min-h-0 outline-none",
        fileTableShell: "h-full w-full min-h-0",
        footerAlerts: "flex flex-col gap-tools",
        footerAlert: "flex items-center gap-tools max-w-modal-compact p-tight",
        footerInfoAlert: "flex items-center gap-tools max-w-modal-compact p-tight text-foreground/70",
        footerActionsStack: "flex flex-col gap-tools sm:items-end sm:justify-end",
        footerActionsRow: "flex flex-wrap items-center justify-end gap-tools",
        footer: surface.chromeEx.workflowFooter,
        inlineBlock: "inline-block",
        cancelButton: "font-medium",
        primaryButton: "font-bold px-stage min-w-button",
        fileCountChipClassNames: {
            content: `${text.code} font-bold`,
        } as const,
    } as const,
} as const;
const settingsTrackingStyle = {
    wide: {
        letterSpacing: "var(--tt-tracking-wide)",
    },
    ultra: {
        letterSpacing: "var(--tt-tracking-ultra)",
    },
} as const;
const settingsSliderValueBadgeStyle = {
    minWidth: "var(--tt-badge-min-width)",
} as const;
export const form = {
    sectionMarginTop: "mt-panel",
    sectionCard: `${surface.surface.panelRaised} overflow-hidden`,
    sectionHeader: `${surface.chromeEx.headerPassive} ${bgBackground40} px-panel py-panel`,
    sectionHeaderStack: "min-w-0 flex flex-col gap-tight",
    sectionTitle: text.headingSection,
    sectionDescription: text.caption,
    sectionBody: "p-panel",
    sectionContentStack: "space-y-tight",
    bodyStackPanel: "space-y-panel py-panel",
    stackTools: "flex flex-col gap-tools",
    systemRow: "flex flex-col gap-tight",
    systemRowHeader: "flex items-center justify-between h-row px-panel",
    systemRowLabel: "text-scaled text-foreground/80 font-medium",
    systemRowControl: "flex items-center gap-tools whitespace-nowrap",
    systemRowHelper: `px-panel ${text.caption}`,
    systemStatusChip: `${text.bodyStrong} tracking-tight`,
    systemNoticeStack: "mt-panel flex flex-col gap-tight",
    systemNoticeBody: "text-scaled text-foreground/80",
    blockStackTight: "space-y-tight",
    blockRowBetween: "flex justify-between items-center",
    switchBlock: "flex flex-col gap-tight",
    switchRow: "flex justify-between items-center h-control-row",
    switchLabel: "text-scaled text-foreground/80 font-medium",
    switchSliderLabel: "text-scaled text-foreground/90 font-medium",
    trackingWideStyle: settingsTrackingStyle.wide,
    sliderValueBadge: `font-medium bg-content2 px-tight py-tight ${roundedMedium} text-center`,
    sliderValueBadgeStyle: settingsSliderValueBadgeStyle,
    sliderValueText: "font-mono text-scaled text-foreground/80",
    slider: "opacity-90",
    bufferedInputWrapperBase: `h-button ${transition.fast}`,
    bufferedInputWrapperEnabled: "group-hover:border-primary/50",
    bufferedInputWrapperDisabled: visuals.state.disabled,
    bufferedInputTextMono: "text-scaled text-foreground/90 font-mono tracking-tight",
    bufferedInputTextDefault: "text-scaled text-foreground/90 font-medium",
    bufferedInputLabel: `${text.label} mb-tight`,
    inputActionRow: "flex w-full items-end gap-tools justify-end",
    inputActionFill: "flex-1 min-w-0",
    inputEndIcon: "text-foreground/40 shrink-0 toolbar-icon-size-sm",
    daySelectorButton: `h-button px-panel shrink-0 font-semibold tracking-wider uppercase bg-primary/10 text-primary text-scaled min-w-0 ${visuals.interactive.buttonPrimary}`,
    daySelectorSelected: "font-bold",
    daySelectorUnselected: "text-foreground/60",
    daySelectorList: "flex flex-wrap gap-tools",
    buttonRow: "flex",
    languageRow: "flex items-center justify-between gap-panel",
    interfaceRow: "flex items-center justify-between gap-panel",
    interfaceRowInfo: "min-w-0",
    interfaceRowActions: "flex gap-tools shrink-0 py-panel",
    rawConfigHeader: "flex items-center justify-between gap-panel",
    rawConfigFeedback: "mt-tight",
    rawConfigStatusSuccess: "text-label text-success",
    rawConfigStatusDanger: "text-label text-danger",
    rawConfigCode: "font-mono text-scaled text-foreground/80",
    rawConfigPanel: surface.surface.panelInfo,
    divider: "my-panel opacity-50",
    selectClassNames: {
        base: "min-w-0",
        mainWrapper: "min-w-0",
        innerWrapper: "min-w-0",
        trigger: "h-button min-w-0 px-panel",
        value: "min-w-0 text-left text-scaled font-medium",
        selectorIcon: "shrink-0",
    } as const,
    sliderClassNames: { thumb: "shadow-small" } as const,
    rawConfigTextarea:
        "w-full resize-none border-none bg-transparent px-panel py-panel leading-relaxed selection:bg-primary/40 focus:outline-none",
    locationEditorRoot: `${surface.surface.panelInfo} p-panel space-y-panel`,
    locationEditorDescription: "text-label text-foreground/60 leading-snug",
    locationEditorCaption: "text-scaled font-semibold text-foreground/70",
    locationEditorError: "text-label text-danger",
    locationEditorRow: "flex flex-col gap-tight",
    locationEditorIconWrap: `shrink-0 self-start flex items-center justify-center`,
    locationEditorIcon: "toolbar-icon-size-xl text-primary",
    locationEditorInputLeadingIcon: "toolbar-icon-size-md text-foreground/50",
    locationEditorInputBrowseButton: "pointer-events-auto text-foreground/50",
    locationEditorInputClassNames: {
        inputWrapper:
            "surface-layer-1 border border-default/50 shadow-none !ring-0 !ring-offset-0 data-[focus=true]:!ring-0 data-[focus-visible=true]:!ring-0 focus-within:border-primary/60",
    } as const,
    locationEditorField: "flex-1 min-w-0 space-y-tight",
    locationEditorPathRow: "flex flex-col gap-tight",
    locationEditorHeader: "shrink-0 min-w-0",
    locationEditorLabelInputRow: "flex items-center gap-tools min-w-0",
    locationEditorLabelColumn: "shrink-0 w-24",
    locationEditorCompactLabelColumn: "shrink-0 w-auto",
    locationEditorValueColumn: "flex-1 min-w-0",
    locationEditorInlineRow: "flex flex-wrap items-baseline gap-tight min-w-0",
    locationEditorInlineLabel: "text-label text-foreground/55",
    locationEditorInlineValue: `${surface.text.code} break-all min-w-0`,
    locationEditorActionRow: "flex flex-col gap-tools sm:flex-row sm:items-start",
    locationEditorInputWrap: "flex-1 min-w-0",
    locationEditorBrowseWrap: "shrink-0",
    locationEditorValidationRow: "h-status-chip flex items-center",
    locationEditorValidationHint: "text-label text-foreground/50",
    locationEditorValidationWarning: "text-label text-warning",
    locationEditorFeedbackSlot: "overflow-hidden",
    workflow: {
        root: "p-panel flex flex-col flex-1 min-h-0 overflow-y-auto overlay-scrollbar",
        fillRoot: "p-panel flex flex-1 min-h-0 flex-col overflow-hidden",
        section: "flex flex-col gap-panel",
        fillSection: "flex min-h-0 flex-1 flex-col gap-panel",
        fillBody: "flex min-h-0 flex-1 flex-col",
        label: `${text.label} flex items-center gap-tools`,
        labelIcon: "toolbar-icon-size-md",
        gatePanel: `p-panel flex flex-col gap-panel ${surface.role.panel}`,
        gatePromptRow: "flex items-center gap-tools font-mono text-label uppercase tracking-widest text-foreground/40",
        gatePromptIcon: "toolbar-icon-size-md text-foreground/50",
        destinationRow: "flex gap-tools group items-center",
        destinationInputWrap: "w-full flex-1",
        destinationInputIcon: "toolbar-icon-size-md text-primary",
        actionIcon: "toolbar-icon-size-md text-foreground/50",
        status: `h-status-chip flex items-center gap-tools min-w-0 ${text.codeMuted}`,
        statusIcon: "toolbar-icon-size-md shrink-0",
        statusSuccessIcon: "toolbar-icon-size-md shrink-0 text-success",
        statusInfoIcon: "toolbar-icon-size-md shrink-0 text-foreground/40",
        statusMessage: "font-bold truncate",
        gateActionsRow: "flex justify-end",
        gateConfirmButton: "font-bold",
        flagsDivider: "my-panel bg-foreground/25",
        flagsCheckboxes: "flex flex-col gap-tools",
        flagsItemLabel: "flex items-center",
        flagsItemDivider: "bg-content1/5",
        flagsIcon: "toolbar-icon-size-md mr-2 text-foreground/50",
    } as const,
    connection: {
        localHeader: "flex items-center justify-between",
        topRow: "flex flex-col gap-tools sm:flex-row sm:items-start sm:justify-between",
        profileTitle: `${text.headingSection} truncate`,
        profileEndpoint: `${text.caption} font-mono break-all`,
        iconSmall: "toolbar-icon-size-sm shrink-0",
        inputHeight: "h-button",
        statusFooter: "border-t border-default/10 pt-panel",
        statusFooterRow: "flex items-start gap-tools",
        insecureAuthWarning: "text-label text-warning",
    } as const,
} as const;
const torrentHeader = {
    cellBase: `relative flex items-center h-row border-r border-content1/10 ${transition.fast} group select-none overflow-visible box-border border-l-2 border-l-transparent`,
    cellSortable: "cursor-pointer hover:bg-content1/10",
    cellStatic: "cursor-default",
    cellOverlay: "bg-content1/90 cursor-grabbing",
    cellDefault: bgTransparent,
    cellOverlayShadow: surface.atom.shadowPanel,
    cellDragging: "opacity-30",
    cellIdle: "opacity-100",
    activatorBase:
        "flex items-center overflow-hidden h-full truncate whitespace-nowrap text-ellipsis box-border leading-none flex-1 gap-tools text-scaled font-bold uppercase text-foreground/60 pl-tight pr-tight",
    activatorOverlay: "text-foreground",
    activatorAlignCenter: "justify-center",
    activatorAlignEnd: "justify-end",
    activatorSelection: "justify-center",
    activatorTrackingStyle: {
        letterSpacing: "var(--tt-tracking-tight)",
    } as const,
    sortIcon: "text-primary shrink-0 toolbar-icon-size-sm",
    sortIconVisible: "opacity-100",
    sortIconHidden: "opacity-0",
    resizeHandle:
        "absolute right-0 top-0 h-full cursor-col-resize touch-none select-none flex items-center justify-end z-overlay w-handle",
    resizeBarStyle: {
        width: "var(--tt-divider-width)",
    } as const,
    resizeBarBase: `bg-foreground/10 ${transition.fast} rounded-full h-resize-h`,
    resizeBarHover: "group-hover:bg-primary/50",
    resizeBarActive: "bg-primary h-resize-h",
} as const;
const contextStatusBadge = tableControl.contextStatusBadge;
const tableShellControl = {
    base: "relative flex-1 h-full min-h-0 flex flex-col",
    panel: "relative flex-1 h-full min-h-0 flex flex-col overflow-hidden",
    island: workbenchIslandShell,
} as const;
const tableHostControl = {
    root: "flex-1 min-h-0 flex flex-col h-full overflow-hidden relative select-none outline-none",
    scroll: "relative flex-1 h-full min-h-0 overflow-y-auto w-full overlay-scrollbar",
    scrollStyle: {
        scrollbarGutter: "stable",
    } as const,
    canvas: "relative w-full min-w-max",
} as const;
const tableRowControl = {
    base: "group hover:bg-primary/5",
    content: registry.control.table.rowClass.content,
    hover: registry.control.table.rowClass.hover,
    selected: registry.control.table.rowClass.selected,
    context: registry.control.table.rowClass.context,
    dragging: registry.control.table.rowClass.dragging,
    dragCursorEnabled: registry.control.table.rowClass.dragCursorEnabled,
    dragCursorDisabled: registry.control.table.rowClass.dragCursorDisabled,
    shell: registry.control.table.rowClass.shell,
} as const;
const tableDragOverlayControl = {
    base: `pointer-events-none absolute inset-x-0 ${panelControl.overlay} px-panel box-border`,
    ghost: `pointer-events-none absolute inset-x-0 ${roundedPanel} border border-default/10 bg-content1/50 px-panel box-border opacity-70 backdrop-blur-md`,
    badge: `pointer-events-none absolute right-tight top-tight ${roundedFull} border border-default/15 ${bgBackground90} px-tight py-1 text-label font-semibold text-foreground/80 shadow-small backdrop-blur-md`,
    content: "flex h-full w-full items-center",
    shadow: tableControl.shadowOverlay,
} as const;
const tableProgressControl = {
    frame: "relative h-full overflow-hidden rounded-full bg-content1/20",
    indicator: "absolute inset-y-0 left-0 transform origin-left rounded-full transition-all duration-300 ease-out",
    cell: "flex flex-col gap-tight w-full min-w-0 py-tight overflow-hidden",
    track: tableControl.progress.track,
    paused: tableControl.progress.paused,
    seeding: tableControl.progress.seeding,
    active: tableControl.progress.active,
    bar: "h-indicator",
    metricsRow: "flex min-w-0 items-end justify-between gap-tight font-medium opacity-80",
    secondary: "text-foreground/40",
} as const;
export const table = {
    shellPanelBase: "relative flex-1 h-full min-h-0 flex flex-col",
    shellPanel: "relative flex-1 h-full min-h-0 flex flex-col overflow-hidden",
    shell: workbenchIslandShell,
    headerGroupRow: "flex w-full min-w-max",
    headerPreviewPadding: "px-(--p-tight)",
    columnHeader: torrentHeader,
    hostRoot: "flex-1 min-h-0 flex flex-col h-full overflow-hidden relative select-none outline-none",
    hostBorderRadiusStyle: {
        borderRadius: "inherit",
    } as const,
    header: `flex w-full ${surface.chrome.edgeBottom} ${surface.chrome.sticky}`,
    bodyScroll: "relative flex-1 h-full min-h-0 overflow-y-auto w-full overlay-scrollbar",
    bodyScrollStyle: {
        scrollbarGutter: "stable",
    } as const,
    bodyCanvas: "relative w-full min-w-max",
    noResults: `h-full flex items-center justify-center px-stage ${text.labelDense}`,
    dragOverlayStack: "pointer-events-none relative box-border",
    dragOverlay: `pointer-events-none absolute inset-x-0 ${surface.role.overlay} px-panel box-border`,
    dragOverlayGhost: `pointer-events-none absolute inset-x-0 ${roundedPanel} border border-default/10 bg-content1/50 px-panel box-border opacity-70 backdrop-blur-md`,
    dragOverlayContent: "flex h-full w-full items-center",
    dragOverlayBadge: `pointer-events-none absolute right-tight top-tight ${roundedFull} border border-default/15 ${bgBackground90} px-tight py-1 text-label font-semibold text-foreground/80 shadow-small backdrop-blur-md`,
    marquee: "pointer-events-none absolute rounded-(--r-sm) border border-primary/60 bg-primary/20",
    loadingRoot: "w-full",
    loadingRow: "flex items-center w-full border-b border-content1/5 px-panel",
    loadingSkeletonWrap: "w-full h-indicator",
    loadingSkeleton: `h-full w-full ${roundedMedium} ${bgContent110}`,
    emptyRoot: "h-full flex flex-col items-center justify-center gap-stage px-stage text-foreground/60",
    emptyHintRow: `flex items-center gap-tools ${text.label}`,
    emptyHintTrackingStyle: {
        letterSpacing: "var(--tt-tracking-ultra)",
    } as const,
    emptySubtext: text.labelMuted,
    emptySubtextTrackingStyle: {
        letterSpacing: "var(--tt-tracking-wide)",
    } as const,
    emptyIcon: "text-primary",
    emptyPreview: "w-full max-w-3xl space-y-tight",
    emptyBar: `h-indicator w-full ${roundedFull} ${bgContent120}`,
    emptyPreviewRow: `grid grid-cols-torrent gap-tools ${roundedRaised} ${bgContent110} px-panel py-panel`,
    columnHeaderLabel: `flex items-center gap-tight ${text.labelDense}`,
    columnHeaderLabelTrackingStyle: {
        letterSpacing: "var(--tt-tracking-ultra)",
    } as const,
    columnHeaderIcon: "text-foreground/50 toolbar-icon-size-md",
    columnDefs: {
        nameCell: "flex min-w-0 items-center h-full",
        nameLabel: `font-medium truncate max-w-full ${transition.fast} cap-height-text`,
        nameLabelPaused: "text-foreground/50",
        progressCell: "flex flex-col gap-tight w-full min-w-0 py-tight overflow-hidden",
        progressMetricsRow: "flex min-w-0 items-end justify-between gap-tight font-medium opacity-80",
        progressSecondary: "text-foreground/40",
        progressBar: "h-indicator",
        progressTrack: surface.atom.progressTrack,
        progressIndicatorPaused: surface.atom.progressIndicatorPaused,
        progressIndicatorSeeding: surface.atom.progressIndicatorSeeding,
        progressIndicatorActive: surface.atom.progressIndicatorActive,
        numericMuted: "text-foreground/60 min-w-0",
        numericSoft: "text-foreground/70 min-w-0",
        numericDim: "text-foreground/50 min-w-0",
        peersRow: "flex items-center justify-end gap-tight text-foreground/60 min-w-0",
        peersIcon: "opacity-50 text-current",
        peersDivider: "opacity-30",
        peersSeedCount: "opacity-50",
        statusCellStack: "flex min-w-0 flex-col items-center justify-center gap-tight",
        statusSwarmBadge: contextStatusBadge,
        statusSwarmBadgeLabel: `${text.caption} truncate font-semibold`,
        statusSwarmTone: {
            neutral: "text-foreground/65",
            warning: "text-warning",
            danger: "text-danger",
        } as const,
    } as const,
    speedCell: {
        root: "relative w-full h-full min-w-0 min-h-0",
        sparkline: "absolute inset-0 w-full h-full overflow-visible opacity-50",
        valueRow: "relative z-panel flex items-center h-full pointer-events-none",
        valueText:
            "font-medium drop-shadow-[0_1px_1px_rgba(0,0,0,0.25)] dark:drop-shadow-[0_1px_1px_rgba(255,255,255,0.15)]",
    } as const,
    detailsContentRoot: "flex h-full min-h-0 flex-col gap-panel",
    detailsContentPanel: `flex flex-1 min-h-0 flex-col ${surface.surface.panelInset}`,
    detailsContentWarning: "flex flex-col gap-tools",
    detailsContentRecoveryNote: "mb-tight text-label text-warning/80",
    detailsContentSectionHeader: `border-b border-default/10 px-panel py-panel ${text.labelPrimary}`,
    detailsContentListHost: "flex-1 min-h-0 overflow-hidden",
} as const;
export const diagnostic = {
    statusChipClassNames: {
        base: `${statusChipPattern.base} border border-default/20 bg-content1/70`,
        content: `${text.labelDense} font-semibold`,
    } as const,
    root: "min-h-screen surface-layer-0 text-foreground pb-stage",
    stack: "flex flex-col gap-stage",
    topbar: "flex flex-wrap items-center justify-between gap-tools",
    topbarText: "flex flex-col gap-tight",
    grid: "grid grid-cols-1 lg:grid-cols-2 gap-stage",
    sectionTitle: "text-navbar font-semibold text-foreground",
    panelPrimary: "p-panel",
    panelSecondaryWrap: "lg:border-l lg:border-default/20 lg:pl-panel",
    panelSecondary: "p-panel bg-content1/35",
    stepCard: `surface-layer-2 ${roundedPanel} p-panel flex flex-col gap-stage`,
    stepHeader: "flex flex-col gap-tight",
    optionsStack: "flex flex-col gap-tools",
    optionsWrap: "flex flex-wrap items-center gap-tools",
    optionsGridResponsive: "grid grid-cols-1 sm:grid-cols-2 gap-tools",
    optionButtonFull: "h-auto w-full justify-start whitespace-normal text-left",
    optionButtonLeft: "justify-start text-left whitespace-normal",
    optionLabelStrong: "font-medium",
    executeRow: "flex flex-wrap items-center justify-between gap-stage",
    executeActions: "flex flex-wrap items-center justify-end gap-tools",
    stateRow: "flex flex-wrap items-center gap-tools",
    statePill: `surface-layer-1 ${roundedPill} px-tight py-tight`,
    statePillValue: "font-semibold text-foreground",
    smokeCard: `surface-layer-2 ${roundedPanel} p-panel flex flex-col gap-stage`,
    smokeRows: `surface-layer-1 ${roundedPanel} p-tight flex flex-col divide-y divide-default/10`,
    smokeRow: "py-tight flex flex-wrap items-center justify-between gap-tools",
    verifyCard: `surface-layer-2 ${roundedPanel} p-panel flex flex-col gap-stage`,
    verifyTableWrap: `surface-layer-1 ${roundedPanel} overflow-hidden`,
    verifyTable: "w-full border-separate border-spacing-0 text-left",
    verifyHead: bgBackground40,
    verifyHeadRow: "border-b border-default/15",
    verifyHeaderCell: tableHeaderPattern.compactCell,
    verifyRow: "border-b border-default/10 last:border-b-0",
    verifyCell: tableHeaderPattern.compactCell,
    verifyLabelWrap: "flex flex-col gap-tight",
    systemCard: `surface-layer-2 ${roundedPanel} p-panel flex flex-col gap-stage`,
    systemRows: "flex flex-col gap-tools",
    systemRowCard: `surface-layer-1 ${roundedPanel} p-tight border-l border-default/20 pl-panel flex flex-col gap-tools`,
    systemRowHead: "flex flex-wrap items-center justify-between gap-tools",
    systemStatusRow: "flex flex-wrap items-center gap-stage",
    systemStatusPair: "flex items-center gap-tight",
    systemMeta: "flex flex-wrap items-center gap-stage",
    footer: "fixed bottom-0 left-0 right-0 z-overlay border-t border-default/20 bg-content1/85 p-panel backdrop-blur-xl",
    footerStack: "flex flex-col gap-tools",
    footerRow: "flex flex-wrap items-center justify-between gap-tools",
    footerLeft: "flex flex-wrap items-center gap-tools",
    footerScenarioLabel: "font-semibold text-foreground",
    footerScenario: `surface-layer-1 ${roundedPanel} px-tight py-tight`,
    footerSummary: "truncate flex-1 min-w-0",
    footerSummaryMuted: "text-foreground/50",
    footerRight: "flex items-center gap-tools",
    footerExpected: "whitespace-pre-wrap leading-relaxed border-t border-default/10 pt-tight mt-tight",
    footerExpectedTone: "text-foreground/80",
} as const;
export const workbench = {
    root: "tt-app-shell relative flex min-h-screen w-full flex-col overflow-hidden bg-background text-foreground font-sans selection:bg-primary/20",
    content: "relative z-panel flex w-full flex-1",
    nativeShellBody: "native-shell-body",
    nativeShellInner: "native-shell-inner",
    nativeShellMain: "native-shell-main",
    iconCurrent: "text-current",
    nav: {
        root: "sticky top-0 z-overlay w-full shrink-0 select-none overflow-visible",
        surface: "text-foreground",
        shell: workbenchIslandShell,
        titlebar: "app-titlebar flex w-full items-stretch",
        titlebarBaseStyle: {
            height: "var(--tt-navbar-h)",
            gap: "var(--spacing-panel)",
        } as const,
        main: "flex grow h-full min-w-0 items-center justify-between gap-panel sm:gap-stage py-tight relative",
        left: "flex items-center gap-tight sm:gap-tools min-w-0",
        brandGroup: "flex items-center gap-tight sm:gap-tools pr-tight",
        brandIconWrap: "flex items-center justify-center",
        brandIconStyle: {
            width: "var(--tt-brand-icon-size)",
            height: "var(--tt-brand-icon-size)",
        } as const,
        brandTextWrap: "hidden xl:flex flex-col justify-center ml-tight",
        brandName: "font-bold tracking-tight text-foreground text-base leading-none text-navbar",
        brandVersion: `${text.codeMuted} text-xs font-medium leading-none mt-0.5 text-default-400`,
        primarySeparator: "hidden sm:flex h-sep w-px bg-default-200/50 mx-tight",
        tabsWrap: "hidden xl:flex text-navbar min-w-0",
        tabTitle: "flex items-center gap-tight",
        tabLabel: "hidden 2xl:inline",
        tabIcon: "text-default-400",
        searchWrap: "hidden 2xl:flex",
        searchStyle: {
            width: "var(--tt-search-width)",
            fontSize: "var(--tt-fz-navbar)",
        } as const,
        searchIcon: "text-default-400",
        actions: `flex items-center gap-tight sm:gap-tools ${transition.medium} shrink-0 opacity-100`,
        primaryActions: "flex items-center gap-tight sm:gap-tools min-w-0",
        primaryActionEmphasis: "ring-1 ring-primary/20",
        selectionSeparator: "hidden sm:flex w-px bg-default-200/50 mx-tight",
        selectionSeparatorStyle: {
            height: "calc(var(--tt-navbar-h) / 2)",
        } as const,
        selectionExtraActions: "hidden sm:flex gap-tools",
        selectionPauseEmphasis: "ring-1 ring-warning/30 shadow-sm",
        selectionRecheckEmphasis: "ring-1 ring-default/20 shadow-sm",
        ghostAction: `text-default-400 ${visuals.interactive.buttonGhost}`,
        ghostActionOverflow: "overflow-visible",
        themeMobileWrap: "flex md:hidden",
        mobileStack: "mt-panel flex sm:hidden",
        mobilePanel: "flex min-w-0 flex-1 flex-col gap-panel py-panel",
        mobileSection: "flex flex-col gap-tools",
        mobileTabsWrap: "min-w-0",
        mobileSearchWrap: "w-full",
        mobileActionGrid: "grid grid-cols-2 gap-tools",
        mobileMenuButton: "h-button justify-start px-panel",
        mobileMenuButtonIcon: "text-current",
        mobileUtilityActions: "grid grid-cols-2 gap-tools",
        rehashWrap: "absolute inset-x-6 bottom-0 translate-y-1/2",
        rehashTooltipWrap: "relative group cursor-help",
        rehashTrack: "h-track bg-transparent",
        rehashIndicator: "h-full bg-gradient-to-r from-primary to-secondary shadow-nav",
        windowControls: "hidden md:flex h-full items-stretch divide-x divide-default/20 overflow-hidden",
        windowControlsStyle: {
            paddingLeft: 0,
            paddingRight: 0,
        } as const,
        toneButtonFallback: {
            primary: `text-primary ${visuals.interactive.buttonPrimary}`,
            success: `text-success ${visuals.interactive.buttonDefault}`,
            warning: `text-warning ${visuals.interactive.buttonDefault}`,
            danger: visuals.interactive.buttonDanger,
            neutral: `text-foreground ${visuals.interactive.buttonPrimary}`,
        } as const,
        filterTabsClassNames: {
            base: "",
            tabList:
                "bg-default-100/50 p-tight border border-default-200/50 shadow-inner gap-tight h-navbar-pill overflow-visible",
            cursor: `${bgBackground90} shadow-sm border-default-100 h-navbar-cursor ${roundedFull}`,
            tab: `px-panel font-semibold text-default-500 text-navbar ${visuals.interactive.navItem}`,
        } as const,
        searchInputClassNames: {
            base: transition.medium,
            mainWrapper: "h-navbar-pill",
            input: "text-navbar font-medium text-foreground/90 whitespace-nowrap overflow-hidden text-ellipsis placeholder:opacity-70",
            inputWrapper: `h-full flex items-center gap-tools flex-nowrap font-normal text-default-500 bg-default-100/50 hover:bg-default-200/50 p-tight border border-default-200/50 focus-within:bg-default-100 focus-within:border-primary/20 shadow-inner rounded-full ${transition.fast}`,
        } as const,
        selectionActionsBase: `flex items-center gap-tools ${transition.medium}`,
        selectionActionsEnabled: "opacity-100",
        selectionActionsDisabled: "opacity-30 pointer-events-none grayscale",
    } as const,
    status: {
        surface: "text-foreground",
        iconCurrent: "text-current",
        iconMuted: "opacity-50",
        srOnly: "sr-only",
        statGroup: "flex flex-col gap-tight whitespace-nowrap",
        statGroupDesktop: "hidden sm:flex",
        statGroupEnd: "items-end",
        statGroupStart: "items-start",
        statValueRow: "flex items-center gap-tools",
        statValueText: "text-scaled text-foreground truncate text-right font-semibold",
        statIcon: "text-foreground/30",
        telemetryIconWrap: "inline-flex items-center",
        speedModule: `flex flex-1 items-center h-full min-w-0 gap-tools group ${surface.surface.statusModule} ${transition.slow} group-hover:border-content1/40 group-hover:bg-content1/10`,
        speedModuleGraphWrap: "relative flex flex-1 h-full min-w-0 gap-tools",
        speedModuleGraph: `relative flex-1 h-full min-w-0 min-h-0 py-tight overflow-visible opacity-30 grayscale ${transition.reveal} group-hover:grayscale-0 group-hover:opacity-100`,
        speedModuleGraphCanvas: "absolute inset-0 h-full w-full",
        speedModuleOverlay: "absolute inset-0 flex items-center justify-start px-panel pointer-events-none",
        speedModuleOverlayRow: "flex items-center gap-tools text-foreground",
        speedModuleIconWrap: `flex items-center justify-center rounded-modal ${transition.fast} toolbar-icon-size-xl`,
        speedModuleTextWrap: "flex flex-col gap-tight text-left",
        speedModuleLabel: "text-label font-bold uppercase tracking-0-2 text-foreground/40",
        speedModuleValue: `${text.heading} tracking-tight leading-none`,
        speedSeparator: "w-px bg-content1/10",
        engineButton: `relative flex items-center justify-center rounded-modal border px-panel ${transition.medium} active:scale-95 focus-visible:outline-none focus-visible:ring focus-visible:ring-primary/60 cursor-pointer`,
        engineConnectedWrap: "absolute inset-0 flex items-start justify-end p-tight",
        engineConnectedPulse: "absolute inline-flex rounded-full",
        engineConnectedDot: "relative inline-flex rounded-full bg-current",
        footer: `w-full shrink-0 select-none relative z-overlay overflow-visible ${workbenchIslandShell}`,
        main: "flex items-center justify-between gap-stage",
        speedFull: "hidden sm:flex flex-1 items-center h-full py-tight gap-stage min-w-0",
        speedCompact: "flex sm:hidden flex-1 items-center h-full py-tight min-w-0",
        speedCompactGraphWrap: "relative flex-1 h-full min-h-0",
        speedCompactLayer: "absolute inset-0",
        speedCompactUpLayer: "absolute inset-0 z-panel",
        speedCompactDownGraph: "h-full w-full",
        speedCompactUpGraph: "h-full w-full opacity-60 mix-blend-screen",
        speedCompactOverlay: "relative z-overlay flex items-center justify-center h-full pointer-events-none",
        speedCompactOverlayRow: "flex items-center gap-tight text-center",
        speedCompactColumn: "flex flex-col items-center",
        speedCompactDownIcon: "toolbar-icon-size-md text-success",
        speedCompactUpIcon: "toolbar-icon-size-md text-primary",
        speedCompactValue: `${text.heading} tracking-tight leading-none`,
        speedCompactDivider: "w-px bg-content1/10 mx-tight",
        right: "flex shrink-0 items-center border-l border-content1/10 gap-stage",
        telemetryGrid: "grid gap-x-stage gap-y-tight",
    } as const,
    reconnectToast: "fixed z-toast",
    section: "tt-shell-body flex w-full flex-1 flex-col",
    sectionGapImmersive: "gap-stage",
    sectionGapClassic: "gap-tools",
    immersiveBackgroundRoot: "pointer-events-none absolute inset-0 z-floor",
    immersiveBackgroundBase: "absolute inset-0 bg-background/95",
    immersiveBackgroundPrimaryBlend: "absolute inset-0 mix-blend-screen opacity-50 bg-primary/20",
    immersiveBackgroundSecondaryBlend: "absolute inset-0 mix-blend-screen opacity-40 bg-content1/15",
    immersiveBackgroundNoise: "absolute inset-0 bg-noise opacity-20",
    immersiveBackgroundAccentBottom:
        "absolute left-1/2 -translate-x-1/2 bottom-0 h-shell-accent-large rounded-pill bg-primary/30 blur-glass opacity-40",
    immersiveBackgroundAccentTop:
        "absolute left-1/2 -translate-x-1/2 top-0 h-shell-accent-medium rounded-pill bg-primary/30 blur-glass opacity-35",
    immersiveNavbarWrap: `${workbenchIslandShell} shadow-hud`,
    immersiveMainWrap: `tt-shell-no-drag ${workbenchMainShell} flex-1 min-h-0 h-full shadow-hud`,
    immersiveMain: "flex-1 min-h-0 h-full overflow-hidden border bg-background/20 shadow-inner",
    immersiveHudSection: "tt-shell-no-drag grid gap-panel",
    immersiveHudCard:
        "glass-panel relative overflow-hidden border border-content1/10 bg-background/55 p-panel shadow-hud",
    immersiveHudDismissButton:
        "absolute rounded-pill bg-content1/20 p-tight text-foreground/60 transition hover:bg-content1/40 hover:text-foreground",
    immersiveHudCardContent: "flex items-start gap-workbench",
    immersiveHudIconWrap: "flex size-icon-btn-lg items-center justify-center rounded-panel",
    immersiveHudTextWrap: "flex-1",
    immersiveHudTextLabel: `mt-tight ${text.bodyStrong}`,
    immersiveHudTextDescription: `mt-panel ${text.caption}`,
    immersiveStatusWrap: `tt-shell-no-drag ${workbenchIslandShell} bg-background/75 shadow-hud blur-glass`,
    classicStack: "flex-1 min-h-0 h-full flex flex-col gap-tools",
    classicMainWrap: "tt-shell-no-drag flex-1 min-h-0 h-full",
    classicStatusWrap: "tt-shell-no-drag",
} as const;
export const split = {
    emptyText: `${text.bodyStrong} text-foreground/30`,
    emptyPanel: "flex h-full items-center justify-center border-default/10 text-center",
    panelGroup: "flex-1 min-h-0",
    panel: "min-h-0",
    root: "flex flex-col h-full min-h-0 overflow-hidden gap-tools",
    contentStack: "flex flex-col flex-1 min-h-0 gap-panel",
    surfacePanel: "relative flex h-full w-full min-h-0 flex-col overflow-hidden p-panel",
    surfacePanelBody: "relative flex-1 min-h-0 w-full",
    surfacePanelFill: "absolute inset-0 flex min-h-0",
    sectionHeader: "flex items-center justify-between mb-tight shrink-0",
    sectionHeaderActions: "flex items-center gap-tools",
    sectionHeaderMeta: "text-scaled text-foreground/60",
    sectionHeaderCaption: "text-label text-foreground/50",
    sectionHeaderIconButton: `text-foreground/60 ${visuals.interactive.textReveal}`,
    mapStatsTrackingStyle: {
        letterSpacing: "var(--tt-tracking-wide)",
    } as const,
    mapHud: `flex h-full min-w-0 shrink-0 flex-nowrap items-start gap-panel ${mapOverlayCard}`,
    mapHudStat: "flex min-w-0 shrink-0 flex-col gap-tight",
    mapHudStatQuiet: "flex min-w-0 shrink-0 flex-col gap-tight opacity-60",
    mapHudLabel: "text-label text-foreground/45",
    mapHudValue: text.code,
    mapHudValueQuiet: "font-mono text-scaled text-foreground/55",
    mapHudValueWarning: "font-mono text-scaled text-warning",
    mapHudValueDanger: "font-mono text-scaled text-danger",
    mapLegendText: surface.text.muted,
    mapLegendShell: "flex h-full items-stretch gap-panel",
    mapLegendGrid: "grid grid-cols-2 grid-rows-2 gap-panel self-center",
    mapLegendCell: "flex min-w-0 items-center gap-tight",
    mapLegendCellPlaceholder: "invisible",
    mapLegendMode: `flex min-w-0 flex-col justify-center gap-tight border-l ${borderToken} pl-panel`,
    mapLegendModeLabel: "text-label text-foreground/45",
    mapLegendModeValue: text.code,
    mapFrame: "relative z-panel flex-1 min-h-0 overflow-hidden mt-panel",
    mapFrameInner: "relative h-full w-full overflow-hidden isolate",
    mapCanvasLayer: "absolute inset-0 block h-full w-full",
    mapCanvasOverlayLayer: "absolute inset-0 block h-full w-full pointer-events-none",
    mapTooltip: `pointer-events-none absolute z-panel max-w-tooltip ${surface.tooltip.content} ${text.body}`,
    mapTooltipPrimaryLine: "block whitespace-normal font-semibold",
    mapTooltipSecondaryLine: "block whitespace-normal text-foreground/70",
    mapTooltipSwatchGrid: "my-tight grid max-h-24 overflow-y-auto pr-tight",
    mapTooltipInfoStack: "flex flex-col gap-tight",
    mapTooltipSwatch: "inline-block",
    mapLegendItem: "flex items-center gap-tight whitespace-nowrap leading-none min-w-0",
    mapLegendSwatch: "inline-block rounded-none",
    mapLegendSwatchVerified: "bg-success",
    mapLegendSwatchCommon: "bg-primary/35",
    mapLegendSwatchRare:
        "bg-warning/75 bg-[repeating-linear-gradient(135deg,rgba(255,255,255,0.22)_0_1px,transparent_1px_4px)]",
    mapLegendSwatchDead: "border border-danger bg-foreground/12",
    mapLegendSwatchMissing: "bg-foreground/18",
    mapLegendInline: `ml-auto flex h-full shrink-0 ${mapOverlayCard}`,
    mapLegendBelow: `mt-panel shrink-0 self-end ${mapOverlayCard}`,
    mapHudDockRow: "flex w-full min-w-0 flex-nowrap items-stretch gap-panel pb-tight",
    mapPanel: "flex flex-col h-full w-full p-tight",
} as const;
export const contextMenu = {
    panel: `pointer-events-auto absolute z-popover ${surface.role.menu}`,
    header: surface.menu.panelHeader,
    headerIcon: surface.menu.panelHeaderIcon,
    headerText: surface.menu.panelHeaderText,
    sectionHeading: `border-t ${borderToken} pt-panel`,
    sectionHeadingStrong: `border-t ${borderToken} mt-tight pt-tight font-bold`,
    sectionHeadingTrackingStyle: {
        letterSpacing: "var(--tt-tracking-ultra)",
    } as const,
    sectionNestedItem: "pl-stage",
    editorItem: `border-t ${borderToken} p-0`,
    editorWrap: "px-panel pt-panel",
    actionButton: surface.menu.actionButton,
    dangerActionButton: surface.menu.dangerActionButton,
} as const;
export const metricChart = {
    canvasWrap: "w-full relative min-h-0",
    canvas: "block w-full h-full",
    root: "flex flex-col gap-tools h-full min-h-0",
    header: "flex items-center justify-between shrink-0 font-mono text-scaled text-foreground/60",
    metrics: "flex items-center gap-panel",
    downMetric: "flex items-center gap-tight text-success font-bold",
    upMetric: "flex items-center gap-tight text-primary font-bold",
    controls: "flex items-center gap-tight",
    layoutGroup: `${bgContent120} ${roundedPanel} p-tight gap-none mr-tight`,
    layoutButtonActive: `${roundedTight} bg-background shadow-small text-foreground`,
    layoutButtonInactive: `${roundedTight} ${bgTransparent} text-foreground/50`,
    windowGroup: `flex ${bgContent120} ${roundedPill} p-tight`,
    windowButtonActive: `${roundedPill} px-tight min-w-0 font-medium bg-foreground text-background shadow-small`,
    windowButtonInactive: `${roundedPill} px-tight min-w-0 font-medium text-foreground/60`,
    content: "flex-1 min-h-0 flex flex-col gap-panel",
    panel: `flex-1 min-h-0 flex flex-col ${surface.role.panel} p-panel relative`,
    panelLabelWrap: "absolute z-panel pointer-events-none",
    panelLabelSuccess: "uppercase tracking-wider font-bold text-success/60 text-label",
    panelLabelPrimary: "uppercase tracking-wider font-bold text-primary/60 text-label",
    panelSeries: "flex-1 min-h-0",
    graphToneMuted: "text-foreground/30",
    graphToneFallback: "text-primary",
    baselineMuted: "opacity-10",
    baselineActive: "opacity-60",
    areaMuted: "opacity-20",
    glowBlurStdDeviation: 2,
    glowFilterRegion: {
        x: "-20%",
        y: "-20%",
        width: "140%",
        height: "140%",
    } as const,
    areaGradientStops: [
        { offset: "0%", opacity: "0.5" },
        { offset: "100%", opacity: "0" },
    ] as const,
    fillFadeStops: [
        { offset: "0%", opacity: "0" },
        { offset: "10%", opacity: "1" },
        { offset: "90%", opacity: "1" },
        { offset: "100%", opacity: "0" },
    ] as const,
    maskCornerRadiusRatio: 0.2,
    progressBar: {
        track: "relative h-full overflow-hidden rounded-full bg-content1/20",
        indicator: `absolute inset-y-0 left-0 transform origin-left rounded-full ${transition.slow} ease-out`,
    } as const,
    capacityGauge: {
        container: "space-y-tight rounded-xl border bg-content1/15 p-tight",
        containerNormal: `space-y-tight rounded-xl border bg-content1/15 p-tight ${borderToken}`,
        containerInsufficient: "space-y-tight rounded-xl border bg-content1/15 p-tight border-danger/40 bg-danger/5",
        header: `flex items-center justify-between ${text.labelDense} text-foreground/60`,
        headerStyle: {
            fontSize: "var(--tt-font-size-base)",
            letterSpacing: "var(--tt-tracking-ultra)",
        } as const,
        baseTextStyle: {
            fontSize: "var(--tt-font-size-base)",
        } as const,
        path: `${text.codeMuted} text-foreground/40`,
        progressWrap: "h-sep",
        stats: `flex justify-between ${text.codeMuted}`,
        hint: `${text.caption} text-foreground/50`,
        errorRow: "flex items-center justify-between gap-tools",
        progressTrack: "h-full bg-content1/20",
        indicatorNormal: "h-full rounded-full bg-gradient-to-r from-success/50 to-success",
        indicatorInsufficient: "h-full rounded-full bg-gradient-to-r from-danger/70 via-warning/70 to-success/70",
    } as const,
} as const;
export const dashBoard = {
    root: `relative h-full w-full flex flex-col flex-1 min-w-0 min-h-0 overflow-hidden ${transition.medium} border-t border-default/10 bg-transparent`,
    content: "relative flex-1 min-h-0 w-full h-full overflow-hidden",
    contentClassicSurface: "bg-background/40",
    dropOverlay: "pointer-events-none absolute inset-0 flex items-center justify-center z-popover",
    dropOverlayAccent: "absolute inset-2 border border-primary/60",
    dropOverlayIconWrap: "relative z-panel",
    dropOverlayIconTone: "text-primary",
    panelGroup: `flex-1 min-h-0 h-full w-full relative overflow-hidden ${roundedRaised}`,
    mainPanel: "relative flex-1 min-h-0 shadow-medium",
    tableHost: "relative z-panel h-full min-h-0 overflow-hidden",
    resizeHandleBase: `group relative z-panel ${transition.fast} focus:outline-none`,
    resizeHandleHorizontal: "cursor-col-resize",
    resizeHandleVertical: "cursor-row-resize",
    desktopWatermark: "torrent-table-watermark absolute inset-0 z-floor pointer-events-none",
    tableContent: "relative z-panel h-full min-h-0",
    resizeHandleInner: "absolute inset-0 flex items-center justify-center",
    resizeHandleBar: `${transition.fast} bg-foreground/0 group-hover:bg-foreground/10 group-active:bg-primary/50`,
    inspectorPanelBase: "overflow-hidden shadow-medium",
    inspectorPanelHorizontal: "h-full",
    inspectorPanelVertical: "w-full",
    inspectorContent: "h-full min-h-0 flex-1",
    section: "relative flex-1 min-h-0 h-full overflow-hidden",
    fullscreenOverlay: "fixed inset-0 z-dnd",
    fullscreenSection: "relative h-full flex items-center justify-center",
    fullscreenBackdrop: "absolute inset-0 pointer-events-none bg-background/60 backdrop-blur-sm",
    fullscreenPanel: `relative z-panel flex h-full w-full flex-col overflow-hidden bg-content1/80 backdrop-blur-xl border ${borderToken} shadow-medium`,
} as const;
const detailsTable = {
    root: "flex h-full flex-col gap-panel",
    toolbar: `${surface.chrome.sticky} flex items-center justify-between px-tight`,
    toolbarGroup: "flex items-center gap-tools",
    toolbarIconPrimary: "text-primary",
    body: "relative min-h-0 flex-1",
    panel: "min-h-0 flex-1 overflow-hidden",
    scroll: "h-full overflow-auto",
    emptyPanel: split.emptyPanel,
    emptyText: split.emptyText,
    table: "w-full border-separate border-spacing-0 text-left",
    tableHeadRow: `${text.label} text-foreground/40`,
    tableHeadIconMuted: "text-foreground/50",
    tableHeadCellIcon: tableHeaderPattern.iconCell,
    tableHeadCell: tableHeaderPattern.sectionDividerCell,
    tableHeadCellStatus: tableHeaderPattern.statusCell,
    tableBody: text.code,
    bodyCell: "px-tight py-panel align-middle",
    bodyCellNumeric: "px-tight py-panel align-middle text-right tabular-nums",
    stateBadge:
        "inline-flex h-status-chip min-w-0 items-center rounded-panel border border-default/10 bg-content1/35 px-tight",
    tableRow: "group hover:bg-primary/5",
    cellIcon: "border-b border-default/5 py-panel pl-panel pr-tight",
    cellHost: "truncate border-b border-default/5 px-tight py-panel font-sans font-medium text-foreground/80",
    cellAnnounce: "border-b border-default/5 px-tight py-panel text-foreground/50 tabular-nums",
    cellPeers: "border-b border-default/5 px-tight py-panel text-foreground/70",
    cellStatus: `border-b border-default/5 py-panel pl-tight pr-panel text-right ${text.labelPrimary}`,
    statusTone: {
        pending: "text-foreground/50",
        online: "text-success",
        partial: "text-warning",
    } as const,
    announceRow: "flex items-center gap-tight",
    peerRow: "flex items-center gap-tools",
    overlay: "absolute inset-0 z-overlay flex flex-col bg-background/40 backdrop-blur-xl",
    overlayHeader: "flex items-center justify-between border-b border-default/10 px-panel py-panel",
    overlayTitle: "text-label font-bold uppercase tracking-label text-primary",
    overlayBody: "flex-1 p-panel",
    overlayFooter: "flex justify-end gap-tools border-t border-default/10 p-panel",
    inputClassNames: {
        input: "font-mono",
        inputWrapper: "bg-background/40",
    } as const,
} as const;
export const details = {
    root: `h-full min-h-0 flex flex-col outline-none rounded-2xl ${workbenchIslandShell}`,
    rootStandalone: "overflow-y-auto",
    body: "flex-1 min-h-0 overflow-y-auto bg-transparent py-tight overlay-scrollbar",
    bodyFill: "flex flex-col overflow-hidden",
    headerRoot: "grid items-center h-row",
    headerRootEmbedded: "bg-content1/80 border-b border-default/10",
    headerTrackingStyle: {
        gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    } as const,
    headerLeft: "flex flex-1 min-w-0 items-center gap-tight px-tight",
    headerInfoIcon: "text-foreground/50 shrink-0",
    headerTitle: "truncate min-w-0 text-foreground font-semibold",
    headerStatus: `${text.caption} block`,
    headerPrimaryHint: "text-label text-foreground/50",
    headerCenter: "flex min-w-0 items-center justify-center px-tight overflow-hidden",
    headerTabs:
        "flex h-full min-w-0 max-w-full items-stretch gap-tight overflow-x-auto overflow-y-hidden px-tight scrollbar-hide",
    headerTabBase: `group text-navbar font-semibold relative flex h-full shrink-0 items-center px-panel py-panel text-foreground/60 ${transition.fast}`,
    headerTabActive: "text-foreground/85 font-semibold",
    headerTabInactive: "bg-transparent hover:text-foreground/85",
    headerTabHoverGlow:
        "pointer-events-none absolute left-0 right-0 rounded-full bg-foreground/10 blur-lg opacity-0 transition-opacity duration-150 group-hover:opacity-100",
    headerTabHoverGlowStyle: {
        left: "var(--spacing-tight)",
        right: "var(--spacing-tight)",
        bottom: "calc(var(--spacing-tight) * 0.35)",
        height: "calc(var(--spacing-panel) * 0.9)",
    } as const,
    headerTabLightBloom: "pointer-events-none absolute left-0 right-0 rounded-full bg-primary/30 blur-lg opacity-100",
    headerTabLightBloomStyle: {
        left: "var(--spacing-tight)",
        right: "var(--spacing-tight)",
        bottom: "calc(var(--spacing-tight) * 0.15)",
        height: "calc(var(--spacing-panel) * 1.05)",
        boxShadow:
            "0 calc(var(--tt-divider-width) * 1.5) calc(var(--spacing-panel) * 0.7) rgba(var(--heroui-primary-500), 0.22)",
    } as const,
    headerTabLightSource: "pointer-events-none absolute left-0 right-0 rounded-full bg-primary",
    headerTabLightSourceStyle: {
        left: "var(--spacing-tight)",
        right: "var(--spacing-tight)",
        bottom: "calc(var(--spacing-tight) * 0.7)",
        height: "calc(var(--tt-divider-width) * 1.25)",
        opacity: 0.98,
        filter: "blur(0.4px)",
        boxShadow:
            "0 0 calc(var(--tt-divider-width) * 1.8) rgba(var(--heroui-primary-500), 0.9), 0 0 calc(var(--spacing-tight) * 0.65) rgba(var(--heroui-primary-500), 0.36)",
    } as const,
    headerRight: "flex min-w-0 shrink-0 items-center justify-self-end justify-end gap-tight px-tight",
    headerContextActions: "flex shrink-0 items-center gap-tight",
    headerContextActionButton:
        "border border-primary/30 bg-transparent text-foreground/70 transition-colors duration-150 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 focus-visible:ring-offset-0",
    headerContextDivider: "h-status-chip w-px bg-foreground/12 mx-tight",
    speedRoot: "flex-1 min-h-0 flex flex-col",
    speedStandaloneSurface: "flex-1 p-stage flex flex-col min-h-0",
    speedEmbeddedSurface: "flex-1 h-full p-stage flex flex-col min-h-0",
    speedChartHost: "flex-1 min-h-0",
    speedCheckingAlert: "mb-tight shrink-0 text-scaled text-warning",
    speedCollectingPanel: `mb-tight shrink-0 rounded-2xl border ${borderToken} bg-background/20 p-panel text-scaled text-foreground/50`,
    generalRoot: "flex flex-col gap-stage px-stage pb-stage",
    generalSection: `flex flex-col gap-panel p-panel ${surface.surface.panelInfo}`,
    generalSectionHeader: "flex items-center justify-between gap-tools",
    generalSectionHeading: "min-w-0",
    generalSectionTitle: text.headingSection,
    generalSectionDescription: "text-label text-foreground/55",
    generalSummaryGrid: "grid gap-tools md:grid-cols-2 xl:grid-cols-3",
    generalMetricGrid: "grid gap-tools md:grid-cols-2",
    generalMetricRow:
        "flex min-w-0 items-start justify-between gap-panel rounded-panel border border-default/10 surface-layer-1 px-panel py-panel",
    generalMetricRowBlock:
        "flex min-w-0 flex-col gap-tight rounded-panel border border-default/10 surface-layer-1 px-panel py-panel",
    generalMetricContent: "min-w-0 flex-1",
    generalMetricLabel: `${text.caption} text-foreground/55 uppercase tracking-wide`,
    generalMetricValue: `${text.bodyStrong} min-w-0 text-right`,
    generalMetricValueBlock: `${text.bodyStrong} min-w-0`,
    generalMetricMuted: `${text.body} text-foreground/55`,
    generalMetricCode: `${text.codeMuted} break-all`,
    generalMetricStack: "flex min-w-0 flex-col gap-tight",
    generalMetricPair: "flex items-center gap-tight text-foreground/75",
    generalMetricActions: "flex shrink-0 items-center gap-tight self-start sm:self-center",
    generalSectionActionButton:
        "rounded-panel border border-default/10 bg-content1/20 px-panel py-tight text-foreground/70 transition-colors duration-150 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 focus-visible:ring-offset-0",
    generalStatusBadge: contextStatusBadge,
    generalStatusBadgeLabel: `${text.caption} font-semibold`,
    generalStatusTone: {
        neutral: "text-foreground/70",
        warning: "text-warning",
        danger: "text-danger",
    } as const,
    generalCommentValue: `${text.body} whitespace-pre-wrap break-words text-foreground/80`,
    generalUnavailable: `${text.body} text-foreground/45 italic`,
    generalSummaryName: `${text.bodyStrong} truncate`,
    generalSummaryStatus: "min-w-0",
    generalProgressWrap: "flex min-w-0 flex-col gap-tight",
    generalProgressMetrics: "flex items-center justify-between gap-tools tabular-nums",
    generalProgressBar: "h-track",
    generalProgressTrack: table.columnDefs.progressTrack,
    generalProgressIndicatorPaused: table.columnDefs.progressIndicatorPaused,
    generalProgressIndicatorSeeding: table.columnDefs.progressIndicatorSeeding,
    generalProgressIndicatorActive: table.columnDefs.progressIndicatorActive,
    table: detailsTable,
} as const;

export const formControl = {
    checkboxPrimaryClassNames: { wrapper: "after:bg-primary" } as const,
    checkboxMarginRightClassNames: { base: "mr-tight" } as const,
    checkboxLabelBodySmallClassNames: {
        base: "items-center",
        label: text.bodySmall,
    } as const,
    prioritySelectClassNames: {
        base: "min-w-status-chip",
        mainWrapper: "min-w-status-chip",
        trigger: `${details.headerContextActionButton} min-w-status-chip rounded-full border border-default/50 bg-transparent px-tight text-foreground/85`,
        value: `${text.bodySmall} leading-none text-foreground/85`,
        selectorIcon: "toolbar-icon-size-sm shrink-0 text-foreground/60",
    } as const,
    priorityHeaderSelectClassNames: {
        base: "min-w-status-chip",
        mainWrapper: "min-w-status-chip",
        trigger: `min-w-status-chip border-b border-default/60 bg-transparent px-tight text-foreground/85`,
        value: `${text.labelDense} leading-none text-foreground/85`,
        selectorIcon: "toolbar-icon-size-sm shrink-0 text-foreground/50",
    } as const,
    statusChipClassNames: {
        base: statusChipPattern.base,
        content: statusChipPattern.content,
    } as const,
    statusChipMutedPrimaryClassNames: {
        base: `${statusChipPattern.base} border border-primary/18 bg-primary/8 dark:border-primary/22 dark:bg-primary/12`,
        content: `${statusChipPattern.content} text-primary/72 dark:text-primary/62`,
    } as const,
    statusChipContainer: statusChipPattern.container,
    statusChipContent: statusChipPattern.contentWrap,
    statusChipWarningIcon: statusChipPattern.warningIcon,
    statusChipCurrentIcon: statusChipPattern.currentIcon,
    statusChipLabel: statusChipPattern.label,
} as const;
export const commandPalette = {
    overlay: "fixed inset-0 z-popover",
    backdrop: `absolute inset-0 ${bgBackground90} backdrop-blur-xl`,
    section: "relative h-full flex items-start justify-center",
    panel: `${surface.role.modal} relative z-panel w-full max-w-2xl`,
    input: "rounded-none border-0 bg-transparent px-panel py-panel text-base font-semibold outline-none placeholder:text-foreground/50",
    list: "max-h-command-palette overflow-y-auto px-panel py-panel",
    groupWrap: "pb-panel",
    item: "glass-panel mt-tight flex cursor-pointer flex-col border border-content1/10 bg-background/80 py-panel px-panel text-left transition hover:border-foreground/40 hover:bg-background/90 focus:border-primary focus:outline-none",
    itemRow: "flex items-center justify-between text-sm font-semibold text-foreground",
    shortcutWrap: `flex gap-tools ${text.codeCaption} text-foreground/50`,
    sectionLabel: "text-label font-semibold uppercase tracking-0-2 text-default-500",
    shortcutKey: `${roundedFull} border border-foreground/30 px-tight py-tight`,
    description: `${text.bodySmall} text-foreground/70`,
    empty: `py-panel text-center ${text.caption}`,
    outcome: "border-t border-default/20 px-panel py-tight text-xs font-medium",
} as const;
export const input = {
    mono: {
        input: "font-mono text-scaled selection:bg-primary/20 selection:text-foreground !outline-none focus:!outline-none focus-visible:!outline-none",
        inputWrapper: `surface-layer-1 ${transition.fast} shadow-none group-hover:border-default/10`,
    } as const,
    monoEmphasized: {
        inputWrapper: "surface-layer-1 border border-default/10 shadow-none focus-within:border-primary/70",
        content: "",
        input: "bg-transparent text-scaled font-mono text-foreground placeholder:text-foreground/30",
    } as const,
    codeTextareaClassNames: {
        ...form.locationEditorInputClassNames,
        base: "w-full",
        innerWrapper: "w-full",
        input: `${text.code} bg-transparent p-panel text-foreground placeholder:text-foreground/30`,
    } as const,
    fillCodeTextareaFrame: `${form.locationEditorInputClassNames.inputWrapper} flex h-full min-h-0 w-full flex-1 flex-col overflow-hidden ${roundedPanel}`,
    fillCodeTextarea: `${text.code} overlay-scrollbar box-border block h-full min-h-0 w-full flex-1 resize-none overflow-y-auto bg-transparent p-panel leading-tight text-foreground placeholder:text-foreground/30 outline-none`,
} as const;

export const control = {
    panel: {
        glass: panelControl.glass,
        canvas: panelControl.canvas,
        island: workbenchIslandShell,
        base: panelControl.base,
        pane: panelControl.pane,
        inset: panelControl.inset,
        insetFull: panelControl.insetFull,
        insetBordered: panelControl.insetBordered,
        raised: panelControl.raised,
        info: panelControl.info,
        workflow: panelControl.workflow,
        sidebar: panelControl.sidebar,
        overlay: panelControl.overlay,
        module: panelControl.statusModule,
        floating: panelControl.floating,
    },
    modal: {
        surface: {
            base: modalControl.surface.baseClass,
        },
        layout: {
            contentWrapper: modalLayoutControl.contentWrapper,
            row: modalLayoutControl.row,
            headerLead: modalLayoutControl.headerLead,
            titleWrap: modalLayoutControl.titleWrap,
            body: modalLayoutControl.body,
            bodyFlush: modalLayoutControl.bodyFlush,
            sectionStack: modalLayoutControl.sectionStack,
            insetStack: modalLayoutControl.insetStack,
            insetItem: modalLayoutControl.insetItem,
            locationRow: modalLayoutControl.locationRow,
            footerButtonRow: modalLayoutControl.footerButtonRow,
            footerGroup: modalLayoutControl.footerGroup,
            contentStack: modalLayoutControl.contentStack,
            scrollContent: modalLayoutControl.scrollContent,
        },
        size: {
            compact: "w-full max-w-modal-compact",
        },
        wrapper: {
            hidden: modalBaseWrapperHiddenClassNames.wrapper,
        },
        chrome: {
            default: modalChromeClassNames,
            dialog: {
                header: controlChrome.dialogHeader,
                footer: controlChrome.dialogFooter,
                footerEnd: controlChrome.footerEnd,
                footerActionsPadded: controlChrome.footerActionsPadded,
                workflowFooter: controlChrome.workflowFooter,
                headerPassive: controlChrome.headerPassive,
            },
        },
    },
    menu: {
        surface: {
            base: menuControl.surface,
            picker: menuControl.dirPickerSurface,
        },
        list: {
            base: menuSurfaceList,
            classNames: menuListClassNames,
        },
        item: {
            base: menuControl.item.base,
            classNames: menuItemClassNames,
            split: menuControl.item.split,
            strong: menuControl.item.strong,
            nested: menuControl.item.nested,
            pinned: menuControl.item.pinned,
            selectedPrimary: menuControl.item.selectedPrimary,
            flagInlineWrap: menuControl.item.flagInlineWrap,
            checkIconPrimary: menuControl.item.checkIconPrimary,
        },
        chrome: {
            sectionHeading: menuControl.chrome.sectionHeading,
            header: menuControl.chrome.header,
            headerIcon: menuControl.chrome.headerIcon,
            headerText: menuControl.chrome.headerText,
        },
        action: {
            iconButton: menuControl.action.iconButton,
            windowButtonBase: menuControl.action.windowButtonBase,
            windowButtonNeutral: menuControl.action.windowButtonNeutral,
            windowButtonDanger: menuControl.action.windowButtonDanger,
            base: menuControl.action.base,
            danger: menuControl.action.danger,
        },
    },
    tooltip: tooltipControl,
    table: {
        shell: {
            base: tableShellControl.base,
            panel: tableShellControl.panel,
            island: tableShellControl.island,
        },
        header: {
            row: `flex w-full ${semanticTokens.chrome.edgeBottom} ${semanticTokens.chrome.sticky}`,
            groupRow: "flex w-full min-w-max",
            previewPadding: "px-(--p-tight)",
            compactCell: tableHeaderPattern.compactCell,
            sectionDividerCell: tableHeaderPattern.sectionDividerCell,
            iconCell: tableHeaderPattern.iconCell,
            statusCell: tableHeaderPattern.statusCell,
            column: torrentHeader,
        },
        host: {
            root: tableHostControl.root,
            scroll: tableHostControl.scroll,
            scrollStyle: tableHostControl.scrollStyle,
            canvas: tableHostControl.canvas,
        },
        row: tableRowControl,
        dragOverlay: {
            base: tableDragOverlayControl.base,
            ghost: tableDragOverlayControl.ghost,
            badge: tableDragOverlayControl.badge,
            content: tableDragOverlayControl.content,
            shadow: tableDragOverlayControl.shadow,
        },
        progress: tableProgressControl,
        statusChip: {
            context: tableControl.contextStatusBadge,
        },
    },
    input: {
        mono: {
            input: "font-mono text-scaled selection:bg-primary/20 selection:text-foreground !outline-none focus:!outline-none focus-visible:!outline-none",
            inputWrapper: `surface-layer-1 ${transition.fast} shadow-none group-hover:border-default/10`,
        },
        emphasized: {
            inputWrapper: "surface-layer-1 border border-default/10 shadow-none focus-within:border-primary/70",
            content: "",
            input: "bg-transparent text-scaled font-mono text-foreground placeholder:text-foreground/30",
        },
        textarea: {
            codeClassNames: {
                inputWrapper:
                    "surface-layer-1 border border-default/50 shadow-none !ring-0 !ring-offset-0 data-[focus=true]:!ring-0 data-[focus-visible=true]:!ring-0 focus-within:border-primary/60",
                base: "w-full",
                innerWrapper: "w-full",
                input: `${text.code} bg-transparent p-panel text-foreground placeholder:text-foreground/30`,
            } as const,
            fillFrame:
                `surface-layer-1 border border-default/50 shadow-none !ring-0 !ring-offset-0 data-[focus=true]:!ring-0 data-[focus-visible=true]:!ring-0 ` +
                `focus-within:border-primary/60 flex h-full min-h-0 w-full flex-1 flex-col overflow-hidden ${roundedPanel}`,
            fill: `${text.code} overlay-scrollbar box-border block h-full min-h-0 w-full flex-1 resize-none overflow-y-auto bg-transparent p-panel leading-tight text-foreground placeholder:text-foreground/30 outline-none`,
        },
    },
    checkbox: {
        primary: { wrapper: "after:bg-primary" } as const,
        withBodySmallLabel: {
            base: "items-center",
            label: text.bodySmall,
        } as const,
    },
    select: {
        priority: {
            base: "min-w-status-chip",
            mainWrapper: "min-w-status-chip",
            trigger:
                "border border-primary/30 bg-transparent text-foreground/70 transition-colors duration-150 " +
                "hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 " +
                "focus-visible:ring-offset-0 min-w-status-chip rounded-full border-default/50 px-tight text-foreground/85",
            value: `${text.bodySmall} leading-none text-foreground/85`,
            selectorIcon: "toolbar-icon-size-sm shrink-0 text-foreground/60",
        } as const,
        priorityHeader: {
            base: "min-w-status-chip",
            mainWrapper: "min-w-status-chip",
            trigger: "min-w-status-chip border-b border-default/60 bg-transparent px-tight text-foreground/85",
            value: `${text.labelDense} leading-none text-foreground/85`,
            selectorIcon: "toolbar-icon-size-sm shrink-0 text-foreground/50",
        } as const,
    },
    statusChip: {
        base: statusChipControl.base,
        content: statusChipControl.content,
        container: statusChipControl.container,
        contentWrap: statusChipControl.contentWrap,
        warningIcon: statusChipControl.warningIcon,
        currentIcon: statusChipControl.currentIcon,
        label: statusChipControl.label,
        classNames: {
            base: statusChipPattern.base,
            content: statusChipPattern.content,
        } as const,
        mutedPrimary: {
            base: `${statusChipPattern.base} border border-primary/18 bg-primary/8 dark:border-primary/22 dark:bg-primary/12`,
            content: `${statusChipPattern.content} text-primary/72 dark:text-primary/62`,
        } as const,
    },
} as const;

export const fileBrowser = {
    container: "flex flex-col h-full min-h-0 overflow-auto relative scrollbar-hide",
    toolbar: "relative flex items-center gap-tools p-tight border-b border-default-200/50 bg-content1/30 shrink-0",
    toolbarLead: "flex min-w-0 items-center gap-tools shrink-0",
    toolbarActionGroup: "flex items-center gap-tight",
    toolbarGap: "w-add-modal-pane-gap shrink-0",
    toolbarSearchWrap: "w-64 shrink-0 toolbar-icon-hit h-toolbar-icon-hit",
    toolbarSelectionCount:
        "hidden h-button shrink-0 items-center whitespace-nowrap px-panel py-0 text-foreground/70 sm:inline-flex",
    toolbarSelectionMeasure: "pointer-events-none absolute invisible h-button shrink-0 whitespace-nowrap px-panel py-0",
    searchInputClassNames: {
        base: "h-full min-w-0 shrink-0",
        mainWrapper: "h-full w-full",
        inputWrapper: `${details.headerContextActionButton} h-full w-full rounded-full bg-transparent px-tight text-foreground/70`,
        input: `${text.bodySmall} h-full leading-none text-foreground/85 placeholder:text-foreground/40`,
    } as const,
    toolbarSpacer: "flex-1",
    toolsDivider: "h-sep w-divider bg-default-300 mx-tight self-center",
    headerRow:
        "grid grid-cols-file-tree items-center gap-tools px-panel py-tight border-b border-default-200/50 shrink-0",
    headerCheckboxWrap: "flex items-center justify-center min-w-0",
    headerCellName: "truncate inline-flex items-center gap-tools bg-transparent text-foreground/85",
    headerCellCenter: "justify-center gap-tools bg-transparent text-foreground/85",
    headerCellEnd: "justify-end gap-tools bg-transparent text-foreground/85",
    cardHeader: "items-start gap-tools",
    cardHeaderContent: "flex min-w-0 flex-1 items-start gap-tools pl-file-tree-indent",
    cardNameGroup: "flex min-w-0 flex-1 items-start gap-tools",
    cardNameContent: "min-w-0 flex-1",
    cardTitleButton: "block w-full truncate text-left",
    cardTitleText: "block truncate",
    cardDescription: "truncate",
    cardBody: "flex flex-col gap-panel",
    cardFooter: "flex items-center justify-between gap-tools",
    cardFooterGroup: "flex min-w-0 items-center gap-tools",
    virtualCanvas: "relative w-full",
    virtualRow: "absolute top-0 left-0 w-full",
    emptyOverlay: "flex flex-col items-center justify-center h-full text-default-400 gap-tools",
    emptyWrap: "flex flex-1 items-center justify-center",
    emptyIcon: "toolbar-icon-size-md opacity-20",
    emptyText: `${text.body} opacity-50`,
    row: `grid grid-cols-file-tree items-center gap-tools px-panel w-full select-none border-b border-default-100/50 hover:bg-default-100/60 ${transition.fast}`,
    rowDimmed: "opacity-60 grayscale-[0.5]",
    rowCheckboxWrap: "flex items-center justify-center min-w-0",
    rowNameCell: "flex items-center overflow-hidden min-w-0 pr-panel pl-file-tree-indent",
    rowIndentSpacer: "w-file-tree-indent-spacer",
    rowIconWrap: "mr-tight text-default-500 shrink-0",
    rowFolderIcon: "toolbar-icon-size-md fill-default-400/20",
    rowNameBase: "text-scaled truncate cursor-default",
    rowNameFolder: "font-medium text-foreground",
    rowNameFile: "text-foreground/80",
    rowPriorityWrap: "flex items-center justify-center min-w-0",
    rowProgressWrap: "block w-full min-w-0 overflow-hidden",
    rowSizeText: `${text.codeMuted} whitespace-nowrap text-right text-default-400`,
    iconVideo: "toolbar-icon-size-md text-primary",
    iconAudio: "toolbar-icon-size-md text-warning",
    iconImage: "toolbar-icon-size-md text-success",
    iconText: "toolbar-icon-size-md text-default-500",
    iconDefault: "toolbar-icon-size-md text-default-400",
    iconSmall: "toolbar-icon-size-md",
    chevronButton: `file-tree-chevron-hit text-default-400 ${roundedFull} hover:text-foreground hover:bg-default-200/50 ${transition.fast}`,
} as const;
export const heatMap = {
    empty: `${surface.surface.panelRaised} p-panel text-center`,
    emptyMuted: "text-scaled text-foreground/50",
    root: "flex flex-col gap-tools",
    header: "flex items-center justify-between",
    legend: "flex items-center gap-tools",
    legendMuted: "text-scaled text-foreground/50",
    legendItem: "flex items-center gap-tight",
    legendDot: "size-dot rounded-full",
    legendDotRare: "bg-danger",
    legendDotCommon: "bg-primary",
    controls: "flex items-center gap-tight",
    zoomButton: `size-icon-btn ${roundedFull}`,
    zoomIcon: "text-current",
    zoomValue: "font-mono text-scaled text-foreground/60",
    canvas: "w-full h-auto block rounded-2xl cursor-crosshair",
    labelTrackingStyle: {
        letterSpacing: "var(--tt-tracking-ultra)",
    } as const,
} as const;
